stages:
  preprocess:
    cmd: python src/data/preprocess.py --in data/raw/housing.csv --out data --test_size 0.2 --random_state 42 --target median_house_value
    deps:
      - src/data/preprocess.py
      - data/raw/housing.csv
    outs:
      - data/raw/X_train_raw.csv:
          cache: false
      - data/raw/X_test_raw.csv:
          cache: false
      - data/raw/y_train_raw.csv:
          cache: false
      - data/raw/y_test_raw.csv:
          cache: false
      - data/processed/X_train.csv:
          cache: false
      - data/processed/X_test.csv:
          cache: false
      - data/processed/y_train.csv:
          cache: false
      - data/processed/y_test.csv:
          cache: false
      - models/scaler.joblib:
          cache: false

  train:
    cmd: python src/model/train_and_track.py
    deps:
      - src/model/train_and_track.py
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv
      - models/scaler.joblib
    outs:
      - models/best_model.joblib:
          cache: false
