name: CI Pipeline

on:
  push:
    branches:
      - main #run on main branch

jobs:
  lint_test_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint pytest fastapi uvicorn prometheus-fastapi-instrumentator

      - name: Lint code with pylint
        env:
          PYTHONPATH:
        run: |
          pylint --disable=R,C src

      #- name: Run tests with pytest
        #env:
          #PYTHONPATH:
        #run: |
          #pytest tests/test_prediction_pytest.py --maxfail=3 --disable-warnings -q

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t nishijain411/california_housing:latest .

      - name: Push Docker image
        run: docker push nishijain411/california_housing:latest

      - name: Run Docker container
        run: docker run -d -p 8000:8000 --name california_housing_container abc/california_housing:latest
        run: sleep 10

      - name: Run tests
        run: pytest tests/test_prediction_pytest.py --maxfail=3 --disable-warnings -q

      - name: Stop Docker container
        run: docker stop my-api-container
